import Foundation
import AppKit

/// One-time admin escalation that installs two NOPASSWD sudoers helpers so the
/// app can run the Python listener and toggle the system SOCKS proxy without a
/// password prompt on every action.
///
/// Helpers (all root-owned, scoped to specific scripts in the sudoers rule):
///   - `/usr/local/bin/cloak-listener` — runs the bundled Python SNI listener.
///   - `/usr/local/bin/cloak-proxy`    — enables/disables the macOS system SOCKS proxy.
enum SudoPrivilege {
    static let sudoersPath = "/etc/sudoers.d/cloak"
    static let wrapperPath = "/usr/local/bin/cloak-listener"
    static let proxyHelperPath = "/usr/local/bin/cloak-proxy"
    /// Bumped whenever any embedded script changes — forces re-install.
    static let wrapperVersion = "6"

    enum SudoError: LocalizedError {
        case promptCancelled
        case installFailed(String)
        case missingPython

        var errorDescription: String? {
            switch self {
            case .promptCancelled:
                return "Admin permission was cancelled. Cloak needs it once to set up its background helpers."
            case .installFailed(let msg):
                return "Setup failed: \(msg)"
            case .missingPython:
                return "No system Python 3 found. Install Xcode Command Line Tools (`xcode-select --install`)."
            }
        }
    }

    /// Fire-and-forget: ask the installed root wrapper to pkill any python it spawned.
    /// Used on app termination so a crashed/force-quit Cloak doesn't leave a listener
    /// consuming CPU. Safe to call when nothing is running.
    static func killLeftoverListener() {
        guard FileManager.default.isExecutableFile(atPath: wrapperPath) else { return }
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/sudo")
        p.arguments = ["-n", wrapperPath, "--kill-leftover"]
        p.standardOutput = Pipe()
        p.standardError = Pipe()
        try? p.run()
        p.waitUntilExit()
    }

    /// Run the proxy helper passwordless. Returns exit status (0 = success).
    @discardableResult
    static func runProxyHelper(_ args: [String]) -> Int32 {
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/sudo")
        p.arguments = ["-n", proxyHelperPath] + args
        p.standardOutput = Pipe()
        p.standardError = Pipe()
        do { try p.run() } catch { return -1 }
        p.waitUntilExit()
        return p.terminationStatus
    }

    /// True when both helpers are installed and NOPASSWD sudo works against them.
    static func isInstalled() -> Bool {
        listenerHelperReady() && proxyHelperReady()
    }

    static func listenerHelperReady() -> Bool {
        let fm = FileManager.default
        guard fm.isExecutableFile(atPath: wrapperPath),
              fm.fileExists(atPath: sudoersPath)
        else { return false }
        return selfCheck(wrapperPath, expectVersion: wrapperVersion)
    }

    static func proxyHelperReady() -> Bool {
        let fm = FileManager.default
        guard fm.isExecutableFile(atPath: proxyHelperPath),
              fm.fileExists(atPath: sudoersPath)
        else { return false }
        return selfCheck(proxyHelperPath, expectVersion: wrapperVersion)
    }

    private static func selfCheck(_ helper: String, expectVersion: String) -> Bool {
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/sudo")
        p.arguments = ["-n", helper, "--self-check"]
        let out = Pipe()
        p.standardOutput = out
        p.standardError = out
        do {
            try p.run()
            p.waitUntilExit()
            guard p.terminationStatus == 0 else { return false }
            let text = String(data: out.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)?
                .trimmingCharacters(in: .whitespacesAndNewlines)
            return text == expectVersion
        } catch {
            return false
        }
    }

    /// Prompts once for an admin password and installs both helpers + the sudoers rule.
    static func install() throws {
        guard let pythonPath = systemPython() else { throw SudoError.missingPython }

        let user = NSUserName()
        let projectDir = AppSettings.default.resolvedPythonProjectPath
        let configPath = appSupportListenerConfigPath()

        let listenerScript = """
        #!/bin/bash
        # Auto-generated by Cloak. Runs the bundled SNI-spoofing listener as root.
        # The sudoers rule at /etc/sudoers.d/cloak only grants NOPASSWD for
        # running THIS file, so the surface is small and easy to audit.
        set -euo pipefail
        if [ "${1:-}" = "--self-check" ]; then echo "\(wrapperVersion)"; exit 0; fi
        if [ "${1:-}" = "--wrapper-version" ]; then echo "\(wrapperVersion)"; exit 0; fi
        if [ "${1:-}" = "--kill-leftover" ]; then
          /usr/bin/pkill -f \(wrapperPath) >/dev/null 2>&1 || true
          /usr/bin/pkill -f \"\(projectDir)/main.py\" >/dev/null 2>&1 || true
          exit 0
        fi
        export CLOAK_CONFIG=\"\(configPath)\"
        cd \"\(projectDir)\"
        WHEEL_DIR=\"\(projectDir)/wheelhouse\"
        # Ensure macOS packet capture dependency exists.
        if ! \"\(pythonPath)\" -c 'import scapy' >/dev/null 2>&1; then
          \"\(pythonPath)\" -m ensurepip --upgrade >/dev/null 2>&1 || true
          if [ ! -d \"$WHEEL_DIR\" ] || ! ls \"$WHEEL_DIR\"/scapy-*.whl >/dev/null 2>&1; then
            echo \"error: bundled scapy wheel missing. Rebuild release so wheelhouse is included.\" >&2
            exit 12
          fi
          \"\(pythonPath)\" -m pip install -q --disable-pip-version-check --no-index --find-links \"$WHEEL_DIR\" scapy >/dev/null 2>&1 || {
            echo \"error: scapy install from bundled wheel failed.\" >&2
            exit 12
          }
          \"\(pythonPath)\" -c 'import scapy' >/dev/null 2>&1 || {
            echo \"error: scapy import failed after wheel install.\" >&2
            exit 12
          }
        fi
        exec \"\(pythonPath)\" \"\(projectDir)/main.py\" \"$@\"
        """

        let proxyScript = """
        #!/bin/bash
        # cloak-proxy: scoped wrapper that toggles the macOS system SOCKS proxy
        # on every active network service via the whitelisted `networksetup`
        # subcommands. Sudoers grants NOPASSWD only for THIS path.
        set -euo pipefail
        if [ "${1:-}" = "--self-check" ]; then echo "\(wrapperVersion)"; exit 0; fi
        ACTION="${1:-}"
        HOST="${2:-}"
        PORT="${3:-}"
        case "$ACTION" in
          enable)
            if [ -z "$HOST" ] || [ -z "$PORT" ]; then
              echo "usage: $0 enable <host> <port>" >&2; exit 1
            fi
            /usr/sbin/networksetup -listallnetworkservices \\
              | /usr/bin/grep -v '^[*]' | /usr/bin/tail -n +2 \\
              | while IFS= read -r svc; do
                  /usr/sbin/networksetup -setsocksfirewallproxy "$svc" "$HOST" "$PORT" off 2>/dev/null || true
                  /usr/sbin/networksetup -setsocksfirewallproxystate "$svc" on 2>/dev/null || true
                done
            ;;
          disable)
            /usr/sbin/networksetup -listallnetworkservices \\
              | /usr/bin/grep -v '^[*]' | /usr/bin/tail -n +2 \\
              | while IFS= read -r svc; do
                  /usr/sbin/networksetup -setsocksfirewallproxystate "$svc" off 2>/dev/null || true
                done
            ;;
          *)
            echo "usage: $0 enable <host> <port> | disable" >&2; exit 1
            ;;
        esac
        """

        let listenerB64 = Data(listenerScript.utf8).base64EncodedString()
        let proxyB64 = Data(proxyScript.utf8).base64EncodedString()

        let sudoersContent = """
        \(user) ALL=(ALL) NOPASSWD: \(wrapperPath)
        \(user) ALL=(ALL) NOPASSWD: \(proxyHelperPath)
        """
        let sudoersB64 = Data(sudoersContent.utf8).base64EncodedString()

        let shell = """
        set -e
        mkdir -p /usr/local/bin
        echo '\(listenerB64)' | /usr/bin/base64 -D > '\(wrapperPath)'
        chown root:wheel '\(wrapperPath)'
        chmod 755 '\(wrapperPath)'
        echo '\(proxyB64)' | /usr/bin/base64 -D > '\(proxyHelperPath)'
        chown root:wheel '\(proxyHelperPath)'
        chmod 755 '\(proxyHelperPath)'
        echo '\(sudoersB64)' | /usr/bin/base64 -D > '\(sudoersPath)'
        chown root:wheel '\(sudoersPath)'
        chmod 440 '\(sudoersPath)'
        /usr/sbin/visudo -cf '\(sudoersPath)' >/dev/null
        # Best-effort cleanup of obsolete helpers from older versions so they
        # can't be invoked via a stale sudoers rule cached in another process.
        rm -f /usr/local/bin/cloak-xray /usr/local/bin/cloak-tun-routes 2>/dev/null || true
        """

        let appleScriptSource = """
        do shell script "\(escapeForAppleScript(shell))" with administrator privileges with prompt "Cloak needs one-time admin permission so it can start the listener and toggle the system proxy without asking for your password every time."
        """

        var err: NSDictionary?
        if let script = NSAppleScript(source: appleScriptSource) {
            _ = script.executeAndReturnError(&err)
        }
        if let e = err {
            let code = (e[NSAppleScript.errorNumber] as? Int) ?? 0
            if code == -128 { throw SudoError.promptCancelled }
            let msg = (e[NSAppleScript.errorMessage] as? String) ?? "unknown"
            throw SudoError.installFailed(msg)
        }
        guard isInstalled() else {
            throw SudoError.installFailed("Sudoers rule did not activate — try again.")
        }
    }

    /// Removes the sudoers rule and helper scripts (prompts for admin again).
    static func uninstall() throws {
        let shell = """
        rm -f '\(sudoersPath)'
        rm -f '\(wrapperPath)'
        rm -f '\(proxyHelperPath)'
        rm -f /usr/local/bin/cloak-xray /usr/local/bin/cloak-tun-routes
        """
        let source = """
        do shell script "\(escapeForAppleScript(shell))" with administrator privileges with prompt "Remove Cloak's passwordless helpers?"
        """
        var err: NSDictionary?
        if let script = NSAppleScript(source: source) {
            _ = script.executeAndReturnError(&err)
        }
        if let e = err {
            let code = (e[NSAppleScript.errorNumber] as? Int) ?? 0
            if code == -128 { throw SudoError.promptCancelled }
            let msg = (e[NSAppleScript.errorMessage] as? String) ?? "unknown"
            throw SudoError.installFailed(msg)
        }
    }

    /// Returns the absolute path to a usable Python 3, or nil if none.
    static func systemPython() -> String? {
        let candidates = [
            "/usr/bin/python3",
            "/opt/homebrew/bin/python3",
            "/usr/local/bin/python3"
        ]
        let fm = FileManager.default
        for c in candidates where fm.isExecutableFile(atPath: c) {
            return c
        }
        return nil
    }

    /// Writable config path the wrapper passes to the Python listener.
    static func appSupportListenerConfigPath() -> String {
        let fm = FileManager.default
        let base = fm.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        let dir = base.appendingPathComponent("SNISpoofing", isDirectory: true)
        try? fm.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appendingPathComponent("listener-config.json").path
    }

    private static func escapeForAppleScript(_ s: String) -> String {
        var out = ""
        for ch in s {
            switch ch {
            case "\\": out += "\\\\"
            case "\"": out += "\\\""
            default: out.append(ch)
            }
        }
        return out
    }
}
