import Foundation
import AppKit

/// One-time admin-escalation that installs a NOPASSWD sudoers rule so the
/// Python listener can run without a password prompt on every Start.
///
/// The rule is scoped to the current user and to a specific wrapper script
/// we drop at `/usr/local/bin/cloak-listener`. The wrapper just exec's the
/// bundled Python entrypoint — this keeps the sudoers rule tight (no wildcard
/// paths) and lets us rewrite the wrapper without needing a new admin prompt.
enum SudoPrivilege {
    static let sudoersPath = "/etc/sudoers.d/cloak"
    static let wrapperPath = "/usr/local/bin/cloak-listener"

    enum SudoError: LocalizedError {
        case promptCancelled
        case installFailed(String)
        case missingPython

        var errorDescription: String? {
            switch self {
            case .promptCancelled:
                return "Admin permission was cancelled. Cloak needs it once to set up its background helper."
            case .installFailed(let msg):
                return "Setup failed: \(msg)"
            case .missingPython:
                return "No system Python 3 found. Install Xcode Command Line Tools (`xcode-select --install`)."
            }
        }
    }

    /// True if both the wrapper and sudoers rule are in place.
    static func isInstalled() -> Bool {
        let fm = FileManager.default
        guard fm.isExecutableFile(atPath: wrapperPath),
              fm.fileExists(atPath: sudoersPath)
        else { return false }
        // Also verify sudo -n can actually run it; otherwise the rule is stale.
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/sudo")
        p.arguments = ["-n", wrapperPath, "--self-check"]
        let devnull = Pipe()
        p.standardOutput = devnull
        p.standardError = devnull
        do {
            try p.run()
            p.waitUntilExit()
            return p.terminationStatus == 0
        } catch {
            return false
        }
    }

    /// Prompts once for an admin password via the system dialog and installs:
    ///   1) `/usr/local/bin/cloak-listener` (exec wrapper, root-owned)
    ///   2) `/etc/sudoers.d/cloak` (NOPASSWD rule for the current user)
    static func install() throws {
        guard let pythonPath = systemPython() else { throw SudoError.missingPython }

        let user = NSUserName()
        let projectDir = AppSettings.default.resolvedPythonProjectPath
        let configPath = appSupportListenerConfigPath()
        let wrapperScript = """
        #!/bin/bash
        # Auto-generated by Cloak. Runs the bundled SNI-spoofing listener as root.
        # The sudoers rule at /etc/sudoers.d/cloak only grants NOPASSWD for
        # running THIS file, so the surface is small and easy to audit.
        set -e
        if [ "$1" = "--self-check" ]; then exit 0; fi
        export CLOAK_CONFIG=\"\(configPath)\"
        cd \"\(projectDir)\"
        exec \"\(pythonPath)\" \"\(projectDir)/main.py\" \"$@\"
        """

        // Escape for embedding inside the AppleScript `do shell script` literal.
        let wrapperB64 = Data(wrapperScript.utf8).base64EncodedString()
        let sudoersLine = "\(user) ALL=(ALL) NOPASSWD: \(wrapperPath)\n"
        let sudoersB64 = Data(sudoersLine.utf8).base64EncodedString()

        let shell = """
        set -e
        mkdir -p /usr/local/bin
        echo '\(wrapperB64)' | /usr/bin/base64 -D > '\(wrapperPath)'
        chown root:wheel '\(wrapperPath)'
        chmod 755 '\(wrapperPath)'
        echo '\(sudoersB64)' | /usr/bin/base64 -D > '\(sudoersPath)'
        chown root:wheel '\(sudoersPath)'
        chmod 440 '\(sudoersPath)'
        /usr/sbin/visudo -cf '\(sudoersPath)' >/dev/null
        """

        let appleScriptSource = """
        do shell script "\(escapeForAppleScript(shell))" with administrator privileges with prompt "Cloak needs one-time admin permission so it can start the VPN without asking for your password every time."
        """

        var err: NSDictionary?
        if let script = NSAppleScript(source: appleScriptSource) {
            _ = script.executeAndReturnError(&err)
        }
        if let e = err {
            let code = (e[NSAppleScript.errorNumber] as? Int) ?? 0
            // -128 = user cancelled.
            if code == -128 { throw SudoError.promptCancelled }
            let msg = (e[NSAppleScript.errorMessage] as? String) ?? "unknown"
            throw SudoError.installFailed(msg)
        }
        guard isInstalled() else {
            throw SudoError.installFailed("Sudoers rule did not activate — try again.")
        }
    }

    /// Removes the sudoers rule and wrapper (requires admin prompt again).
    static func uninstall() throws {
        let shell = """
        rm -f '\(sudoersPath)'
        rm -f '\(wrapperPath)'
        """
        let source = """
        do shell script "\(escapeForAppleScript(shell))" with administrator privileges with prompt "Remove Cloak's passwordless startup rule?"
        """
        var err: NSDictionary?
        if let script = NSAppleScript(source: source) {
            _ = script.executeAndReturnError(&err)
        }
        if let e = err {
            let code = (e[NSAppleScript.errorNumber] as? Int) ?? 0
            if code == -128 { throw SudoError.promptCancelled }
            let msg = (e[NSAppleScript.errorMessage] as? String) ?? "unknown"
            throw SudoError.installFailed(msg)
        }
    }

    /// Returns the absolute path to a usable Python 3, or nil if none.
    static func systemPython() -> String? {
        let candidates = [
            "/usr/bin/python3",
            "/opt/homebrew/bin/python3",
            "/usr/local/bin/python3"
        ]
        let fm = FileManager.default
        for c in candidates where fm.isExecutableFile(atPath: c) {
            return c
        }
        return nil
    }

    /// Writable config path the wrapper passes to the Python listener.
    static func appSupportListenerConfigPath() -> String {
        let fm = FileManager.default
        let base = fm.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        let dir = base.appendingPathComponent("SNISpoofing", isDirectory: true)
        try? fm.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appendingPathComponent("listener-config.json").path
    }

    private static func escapeForAppleScript(_ s: String) -> String {
        // AppleScript strings: escape backslashes and double quotes only.
        var out = ""
        for ch in s {
            switch ch {
            case "\\": out += "\\\\"
            case "\"": out += "\\\""
            default: out.append(ch)
            }
        }
        return out
    }
}
