import Foundation
import AppKit

/// One-time admin-escalation that installs a NOPASSWD sudoers rule so the
/// Python listener can run without a password prompt on every Start.
///
/// The rule is scoped to the current user and to a specific wrapper script
/// we drop at `/usr/local/bin/cloak-listener`. The wrapper just exec's the
/// bundled Python entrypoint — this keeps the sudoers rule tight (no wildcard
/// paths) and lets us rewrite the wrapper without needing a new admin prompt.
enum SudoPrivilege {
    static let sudoersPath = "/etc/sudoers.d/cloak"
    static let wrapperPath = "/usr/local/bin/cloak-listener"
    static let wrapperVersion = "4"
    static let xrayWrapperPath = "/usr/local/bin/cloak-xray"
    /// `sudo -n cloak-tun-routes up|down <connect_ip> <utun_name>` — IPv4 split routes for TUN mode.
    static let tunRoutesPath = "/usr/local/bin/cloak-tun-routes"

    enum SudoError: LocalizedError {
        case promptCancelled
        case installFailed(String)
        case missingPython

        var errorDescription: String? {
            switch self {
            case .promptCancelled:
                return "Admin permission was cancelled. Cloak needs it once to set up its background helper."
            case .installFailed(let msg):
                return "Setup failed: \(msg)"
            case .missingPython:
                return "No system Python 3 found. Install Xcode Command Line Tools (`xcode-select --install`)."
            }
        }
    }

    /// True if both the wrapper and sudoers rule are in place.
    static func isInstalled() -> Bool {
        let fm = FileManager.default
        guard fm.isExecutableFile(atPath: wrapperPath),
              fm.fileExists(atPath: sudoersPath)
        else { return false }
        // Also verify sudo -n can actually run it; otherwise the rule is stale.
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/sudo")
        p.arguments = ["-n", wrapperPath, "--wrapper-version"]
        let out = Pipe()
        p.standardOutput = out
        p.standardError = out
        do {
            try p.run()
            p.waitUntilExit()
            guard p.terminationStatus == 0 else { return false }
            let text = String(data: out.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)?
                .trimmingCharacters(in: .whitespacesAndNewlines)
            return text == wrapperVersion
        } catch {
            return false
        }
    }

    /// True if the TUN route helper is installed and NOPASSWD works (for **System tunnel (TUN)**).
    static func tunRoutesHelperReady() -> Bool {
        let fm = FileManager.default
        guard fm.isExecutableFile(atPath: tunRoutesPath) else { return false }
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/sudo")
        p.arguments = ["-n", tunRoutesPath, "--self-check"]
        let devnull = Pipe()
        p.standardOutput = devnull
        p.standardError = devnull
        do {
            try p.run()
            p.waitUntilExit()
            return p.terminationStatus == 0
        } catch {
            return false
        }
    }

    /// True if the privileged Xray launcher is installed (required for TUN mode).
    static func xrayWrapperReady() -> Bool {
        let fm = FileManager.default
        guard fm.isExecutableFile(atPath: xrayWrapperPath) else { return false }
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/sudo")
        p.arguments = ["-n", xrayWrapperPath, "--self-check"]
        let devnull = Pipe()
        p.standardOutput = devnull
        p.standardError = devnull
        do {
            try p.run()
            p.waitUntilExit()
            return p.terminationStatus == 0
        } catch {
            return false
        }
    }

    /// Prompts once for an admin password via the system dialog and installs:
    ///   1) `/usr/local/bin/cloak-listener` (exec wrapper, root-owned)
    ///   2) `/etc/sudoers.d/cloak` (NOPASSWD rule for the current user)
    static func install() throws {
        guard let pythonPath = systemPython() else { throw SudoError.missingPython }

        let user = NSUserName()
        let projectDir = AppSettings.default.resolvedPythonProjectPath
        let configPath = appSupportListenerConfigPath()
        let wrapperScript = """
        #!/bin/bash
        # Auto-generated by Cloak. Runs the bundled SNI-spoofing listener as root.
        # The sudoers rule at /etc/sudoers.d/cloak only grants NOPASSWD for
        # running THIS file, so the surface is small and easy to audit.
        set -euo pipefail
        if [ "${1:-}" = "--self-check" ]; then exit 0; fi
        if [ "${1:-}" = "--wrapper-version" ]; then echo "\(wrapperVersion)"; exit 0; fi
        export CLOAK_CONFIG=\"\(configPath)\"
        cd \"\(projectDir)\"
        WHEEL_DIR=\"\(projectDir)/wheelhouse\"
        # Ensure macOS packet capture dependency exists.
        if ! \"\(pythonPath)\" -c 'import scapy' >/dev/null 2>&1; then
          \"\(pythonPath)\" -m ensurepip --upgrade >/dev/null 2>&1 || true
          if [ ! -d \"$WHEEL_DIR\" ] || ! ls \"$WHEEL_DIR\"/scapy-*.whl >/dev/null 2>&1; then
            echo \"error: bundled scapy wheel missing. Rebuild release so wheelhouse is included.\" >&2
            exit 12
          fi
          \"\(pythonPath)\" -m pip install -q --disable-pip-version-check --no-index --find-links \"$WHEEL_DIR\" scapy >/dev/null 2>&1 || {
            echo \"error: scapy install from bundled wheel failed.\" >&2
            exit 12
          }
          \"\(pythonPath)\" -c 'import scapy' >/dev/null 2>&1 || {
            echo \"error: scapy import failed after wheel install.\" >&2
            exit 12
          }
        fi
        exec \"\(pythonPath)\" \"\(projectDir)/main.py\" \"$@\"
        """

        // Escape for embedding inside the AppleScript `do shell script` literal.
        let wrapperB64 = Data(wrapperScript.utf8).base64EncodedString()
        let xrayWrapperScript = """
        #!/bin/bash
        set -euo pipefail
        if [ "${1:-}" = "--self-check" ]; then exit 0; fi
        XRAY_BIN="${1:-}"
        CFG_PATH="${2:-}"
        RES_DIR="${3:-}"
        if [ -z "$XRAY_BIN" ] || [ -z "$CFG_PATH" ] || [ -z "$RES_DIR" ]; then
          echo "usage: $0 <xray_bin> <config_path> <resource_dir>" >&2
          exit 1
        fi
        cd "$RES_DIR"
        exec "$XRAY_BIN" run -c "$CFG_PATH"
        """
        let xrayWrapperB64 = Data(xrayWrapperScript.utf8).base64EncodedString()
        let tunRoutesScript = """
        #!/bin/bash
        set -euo pipefail
        if [ "${1:-}" = "--self-check" ]; then exit 0; fi
        ACTION="${1:-}"
        CONNECT_IP="${2:-}"
        UTUN="${3:-}"
        if [ -z "$ACTION" ] || [ -z "$CONNECT_IP" ] || [ -z "$UTUN" ]; then
          echo "usage: $0 up|down <connect_ip> <utun_name>" >&2
          exit 1
        fi
        GW="$(route -n get default 2>/dev/null | awk '/gateway:/{print $2; exit}')"
        if [ -z "$GW" ]; then
          echo "cloak-tun-routes: no default gateway" >&2
          exit 1
        fi
        case "$ACTION" in
          up)
            route add -host "$CONNECT_IP" "$GW" 2>/dev/null || route change -host "$CONNECT_IP" "$GW" 2>/dev/null || true
            route add -net 0.0.0.0/1 -interface "$UTUN" 2>/dev/null || route change -net 0.0.0.0/1 -interface "$UTUN" 2>/dev/null || true
            route add -net 128.0.0.0/1 -interface "$UTUN" 2>/dev/null || route change -net 128.0.0.0/1 -interface "$UTUN" 2>/dev/null || true
            ;;
          down)
            route delete -net 0.0.0.0/1 -interface "$UTUN" 2>/dev/null || true
            route delete -net 128.0.0.0/1 -interface "$UTUN" 2>/dev/null || true
            route delete -host "$CONNECT_IP" 2>/dev/null || true
            ;;
          *)
            echo "usage: $0 up|down <connect_ip> <utun_name>" >&2
            exit 1
            ;;
        esac
        """
        let tunRoutesB64 = Data(tunRoutesScript.utf8).base64EncodedString()
        let sudoersContent = """
        \(user) ALL=(ALL) NOPASSWD: \(wrapperPath)
        \(user) ALL=(ALL) NOPASSWD: \(xrayWrapperPath)
        \(user) ALL=(ALL) NOPASSWD: \(tunRoutesPath)
        """
        let sudoersB64 = Data(sudoersContent.utf8).base64EncodedString()

        let shell = """
        set -e
        mkdir -p /usr/local/bin
        echo '\(wrapperB64)' | /usr/bin/base64 -D > '\(wrapperPath)'
        chown root:wheel '\(wrapperPath)'
        chmod 755 '\(wrapperPath)'
        echo '\(xrayWrapperB64)' | /usr/bin/base64 -D > '\(xrayWrapperPath)'
        chown root:wheel '\(xrayWrapperPath)'
        chmod 755 '\(xrayWrapperPath)'
        echo '\(tunRoutesB64)' | /usr/bin/base64 -D > '\(tunRoutesPath)'
        chown root:wheel '\(tunRoutesPath)'
        chmod 755 '\(tunRoutesPath)'
        echo '\(sudoersB64)' | /usr/bin/base64 -D > '\(sudoersPath)'
        chown root:wheel '\(sudoersPath)'
        chmod 440 '\(sudoersPath)'
        /usr/sbin/visudo -cf '\(sudoersPath)' >/dev/null
        """

        let appleScriptSource = """
        do shell script "\(escapeForAppleScript(shell))" with administrator privileges with prompt "Cloak needs one-time admin permission so it can start the VPN without asking for your password every time."
        """

        var err: NSDictionary?
        if let script = NSAppleScript(source: appleScriptSource) {
            _ = script.executeAndReturnError(&err)
        }
        if let e = err {
            let code = (e[NSAppleScript.errorNumber] as? Int) ?? 0
            // -128 = user cancelled.
            if code == -128 { throw SudoError.promptCancelled }
            let msg = (e[NSAppleScript.errorMessage] as? String) ?? "unknown"
            throw SudoError.installFailed(msg)
        }
        guard isInstalled() else {
            throw SudoError.installFailed("Sudoers rule did not activate — try again.")
        }
    }

    /// Removes the sudoers rule and wrapper (requires admin prompt again).
    static func uninstall() throws {
        let shell = """
        rm -f '\(sudoersPath)'
        rm -f '\(wrapperPath)'
        rm -f '\(xrayWrapperPath)'
        rm -f '\(tunRoutesPath)'
        """
        let source = """
        do shell script "\(escapeForAppleScript(shell))" with administrator privileges with prompt "Remove Cloak's passwordless startup rule?"
        """
        var err: NSDictionary?
        if let script = NSAppleScript(source: source) {
            _ = script.executeAndReturnError(&err)
        }
        if let e = err {
            let code = (e[NSAppleScript.errorNumber] as? Int) ?? 0
            if code == -128 { throw SudoError.promptCancelled }
            let msg = (e[NSAppleScript.errorMessage] as? String) ?? "unknown"
            throw SudoError.installFailed(msg)
        }
    }

    /// Returns the absolute path to a usable Python 3, or nil if none.
    static func systemPython() -> String? {
        let candidates = [
            "/usr/bin/python3",
            "/opt/homebrew/bin/python3",
            "/usr/local/bin/python3"
        ]
        let fm = FileManager.default
        for c in candidates where fm.isExecutableFile(atPath: c) {
            return c
        }
        return nil
    }

    /// Writable config path the wrapper passes to the Python listener.
    static func appSupportListenerConfigPath() -> String {
        let fm = FileManager.default
        let base = fm.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        let dir = base.appendingPathComponent("SNISpoofing", isDirectory: true)
        try? fm.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appendingPathComponent("listener-config.json").path
    }

    private static func escapeForAppleScript(_ s: String) -> String {
        // AppleScript strings: escape backslashes and double quotes only.
        var out = ""
        for ch in s {
            switch ch {
            case "\\": out += "\\\\"
            case "\"": out += "\\\""
            default: out.append(ch)
            }
        }
        return out
    }
}
